//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTrainingPlanner.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymTrainingPlanner.Common.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        public static string Account_Authenticate_Failed {
            get {
                return ResourceManager.GetString("Account_Authenticate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not allowed to authenticate. Make sure that your email is confirmed..
        /// </summary>
        public static string Account_Authenticate_NotAllowed {
            get {
                return ResourceManager.GetString("Account_Authenticate_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are wrong..
        /// </summary>
        public static string Account_Authenticate_WrongCredentials {
            get {
                return ResourceManager.GetString("Account_Authenticate_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation token is invalid..
        /// </summary>
        public static string Account_ConfirmationToken_Invalid {
            get {
                return ResourceManager.GetString("Account_ConfirmationToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was successfully confirmed..
        /// </summary>
        public static string Account_Email_Confirmed {
            get {
                return ResourceManager.GetString("Account_Email_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is in incorrect format..
        /// </summary>
        public static string Account_Email_Incorrect_Format {
            get {
                return ResourceManager.GetString("Account_Email_Incorrect_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not defined..
        /// </summary>
        public static string Account_Email_Undefined {
            get {
                return ResourceManager.GetString("Account_Email_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked..
        /// </summary>
        public static string Account_Locked {
            get {
                return ResourceManager.GetString("Account_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was not found by provided email..
        /// </summary>
        public static string Account_NotFound {
            get {
                return ResourceManager.GetString("Account_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password requires atleast: 8 characters, one uppercase, one lowercase, one non alphanumeric, one digit..
        /// </summary>
        public static string Account_Password_InvalidFormat {
            get {
                return ResourceManager.GetString("Account_Password_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully created..
        /// </summary>
        public static string Account_Successfully_Created {
            get {
                return ResourceManager.GetString("Account_Successfully_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GymTrainingPlanner - Confirm your Email.
        /// </summary>
        public static string Email_ConfirmationEmail_Subject {
            get {
                return ResourceManager.GetString("Email_ConfirmationEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} can only contain only letters..
        /// </summary>
        public static string Invalid_Format_Letters_Only {
            get {
                return ResourceManager.GetString("Invalid_Format_Letters_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than {MaxLength} characters..
        /// </summary>
        public static string Maximum_Length_Error {
            get {
                return ResourceManager.GetString("Maximum_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please, contact with us for more details..
        /// </summary>
        public static string Something_Went_Wrong {
            get {
                return ResourceManager.GetString("Something_Went_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
